version: "3.8"

services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql

volumes:
  mysql_data:
