CREATE TABLE IF NOT EXISTS clients (
  id VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS accounts (
  id VARCHAR(255) NOT NULL,
  client_id VARCHAR(255) NOT NULL,
  balance FLOAT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS transactions (
  id VARCHAR(255) NOT NULL,
  account_from_id VARCHAR(255) NOT NULL,
  account_to_id VARCHAR(255) NOT NULL,
  amount FLOAT NOT NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id)
);
